CREATE TABLE `t_loan_ledger` (
  `id`              BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
  `loan_id`         VARCHAR(50)   NOT NULL                COMMENT '借据号',
  `company_name`    VARCHAR(200)  NOT NULL                COMMENT '公司名称',
  `credit_code`     CHAR(18)      NOT NULL                COMMENT '企业统一信用代码',
  `loan_amount`     DECIMAL(15,2) NOT NULL                COMMENT '借据金额（元）',
  `interest_rate`   DECIMAL(7,4)  NOT NULL                COMMENT '年利率（%）',
  `loan_date`       DATE          NOT NULL                COMMENT '放款日期',
  `due_date`        DATE          NOT NULL                COMMENT '到期日期',
  `is_green`        TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '是否绿色信贷：0否 1是',
  `is_agriculture`  TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '是否涉农：0否 1是',
  `is_guarantee`    TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '是否有担保：0否 1是',
  `guarantee_org`   VARCHAR(200)      NULL                COMMENT '担保机构名称',
  `status`          TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '台账状态：0草稿 1待复核 2已通过 3已拒绝',
  `submit_by`       VARCHAR(50)       NULL                COMMENT '提交人员工号',
  `submit_time`     DATETIME          NULL                COMMENT '提交时间',
  `review_by`       VARCHAR(50)       NULL                COMMENT '复核人员工号',
  `review_time`     DATETIME          NULL                COMMENT '复核时间',
  `is_approved`     TINYINT(1)        NULL                COMMENT '审批结论：NULL未审 1通过 0拒绝',
  `reject_reason`   VARCHAR(500)      NULL                COMMENT '拒绝原因',
  `remark`          VARCHAR(500)      NULL                COMMENT '备注',
  `created_by`      VARCHAR(50)   NOT NULL                COMMENT '创建人员工号',
  `created_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by`      VARCHAR(50)       NULL                COMMENT '更新人员工号',
  `updated_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted`      TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '软删除：0正常 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_loan_id` (`loan_id`),
  KEY `idx_company_name` (`company_name`),
  KEY `idx_status` (`status`),
  KEY `idx_submit_by` (`submit_by`),
  KEY `idx_loan_date` (`loan_date`),
  KEY `idx_credit_code` (`credit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借据台账主表';